const PDFDocument = require('pdfkit');
const logger = require('../utils/logger');
const { calculateStampDuty } = require('./financials');

/**
 * PDF Document Generator for MutuneRent Pro Official Paperwork
 */
function generateLegalPDF(docType, data) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });

      // Header Banner Styling
      doc.rect(0, 0, doc.page.width, 90).fill('#0f172a');
      doc.fillColor('#10b981').fontSize(22).font('Helvetica-Bold').text('MUTUNERENT PRO', 50, 25);
      doc.fillColor('#94a3b8').fontSize(9).font('Helvetica').text('Enterprise Property Accounting & Legal Paperwork Suite', 50, 52);
      doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold').text(getDocTitle(docType).toUpperCase(), doc.page.width - 250, 35, { align: 'right', width: 200 });

      doc.moveDown(4);
      doc.fillColor('#1e293b');

      switch (docType) {
        case 'lease_agreement':
          renderLeaseAgreement(doc, data);
          break;
        case 'demand_note_7day':
          renderDemandNote(doc, data);
          break;
        case 'quit_notice_30day':
          renderQuitNotice(doc, data);
          break;
        case 'landlord_remittance_statement':
          renderLandlordStatement(doc, data);
          break;
        case 'agent_salary_voucher':
          renderAgentSalaryVoucher(doc, data);
          break;
        case 'etims_tax_receipt':
          renderETIMSReceipt(doc, data);
          break;
        case 'rrt_landlord_complaint':
          renderRRTComplaintForm(doc, data);
          break;
        case 'rrt_tenant_response':
          renderRRTResponseForm(doc, data);
          break;
        default:
          renderGenericDocument(doc, data);
      }

      // Footer
      const bottom = doc.page.height - 50;
      doc.fontSize(8).fillColor('#64748b').text('Generated by MutuneRent Pro Legal Engine • KRA eTIMS & Cap 301 Compliant • Page 1 of 1', 50, bottom, { align: 'center', width: doc.page.width - 100 });

      doc.end();
    } catch (err) {
      logger.error('PDF Generation Error', { docType, error: err.message });
      reject(err);
    }
  });
}

function getDocTitle(docType) {
  const titles = {
    lease_agreement: 'Tenancy Lease Agreement',
    demand_note_7day: '7-Day Rent Demand Note',
    quit_notice_30day: '30-Day Notice to Quit & Vacate',
    landlord_remittance_statement: 'Landlord Remittance Statement',
    agent_salary_voucher: 'Agent Salary & Commission Voucher',
    etims_tax_receipt: 'KRA eTIMS Tax Invoice Receipt',
    rrt_landlord_complaint: 'Rent Restriction Tribunal Complaint Form',
    rrt_tenant_response: 'Rent Restriction Tribunal Response Form'
  };
  return titles[docType] || 'Official Document';
}

function renderLeaseAgreement(doc, data) {
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#0f172a').text('RESIDENTIAL / COMMERCIAL TENANCY LEASE AGREEMENT', { align: 'center' });
  doc.moveDown(1);

  doc.fontSize(9.5).font('Helvetica').fillColor('#334155');
  doc.text(`THIS LEASE AGREEMENT is made this ${data.signing_date || new Date().toLocaleDateString('en-KE')} between:`);
  doc.moveDown(0.5);

  doc.font('Helvetica-Bold').text(`LANDLORD / LESSOR: ${data.landlord_name || 'Property Owner'}`);
  doc.font('Helvetica').text(`Email: ${data.landlord_email || 'N/A'} • Phone: ${data.landlord_phone || 'N/A'}`);
  doc.moveDown(0.5);

  doc.font('Helvetica-Bold').text(`TENANT / LESSEE: ${data.tenant_name || 'Tenant Name'}`);
  doc.font('Helvetica').text(`Tenant Code: ${data.tenant_code || 'N/A'} • ID/Passport: ${data.id_number || 'N/A'} • Phone: ${data.tenant_phone || 'N/A'}`);
  doc.moveDown(0.8);

  doc.font('Helvetica-Bold').text('1. PREMISES & FINANCIAL TERMS:');
  doc.font('Helvetica').text(`Property: ${data.property_name || 'Property Name'} (Unit: ${data.unit_number || 'N/A'})`);
  doc.text(`Monthly Rent: KES ${(data.rent_amount_kes || 0).toLocaleString('en-KE')} payable by the 5th of each month.`);
  doc.text(`Refundable Security Deposit: KES ${(data.deposit_amount_kes || 0).toLocaleString('en-KE')}.`);
  doc.text(`Lease Term: ${data.lease_duration_months || 12} Months commencing ${data.start_date || new Date().toLocaleDateString('en-KE')}.`);
  doc.moveDown(0.8);

  // Step 4.2: Stamp Duty Advisory Box (Section 19, Stamp Duty Act Cap 480)
  const stampDuty = calculateStampDuty({
    monthlyRentKes: data.rent_amount_kes || 0,
    leaseDurationMonths: data.lease_duration_months || 12
  });

  doc.rect(50, doc.y, doc.page.width - 100, 48).fillAndStroke('#f8fafc', '#cbd5e1');
  const stampY = doc.y + 6;
  doc.fillColor('#0369a1').fontSize(8.5).font('Helvetica-Bold').text('STAMP DUTY ADVISORY (KENYA STAMP DUTY ACT CAP 480):', 60, stampY);
  doc.fillColor('#334155').fontSize(8).font('Helvetica').text(`Annual Rental Value: KES ${stampDuty.annual_rent_kes.toLocaleString('en-KE')} | Stamp Duty Payable: KES ${stampDuty.stamp_duty_payable_kes.toLocaleString('en-KE')}`, 60, stampY + 12);
  doc.fillColor('#64748b').text(`Assessment Rate: ${stampDuty.rate_description} • Informational e-Slip Notice`, 60, stampY + 24);
  doc.y = stampY + 45;
  doc.moveDown(0.8);

  // Step 4.1: Signatures & Digital Attestation Block
  doc.fontSize(9.5).fillColor('#0f172a').font('Helvetica-Bold').text('2. SIGNATURES & ATTESTATION:');
  doc.moveDown(0.5);

  if (data.is_digitally_signed || data.signature_hash) {
    // Digital E-Signature Attestation Block
    doc.rect(50, doc.y, doc.page.width - 100, 68).fillAndStroke('#f0fdf4', '#86efac');
    const badgeY = doc.y + 6;
    doc.fillColor('#15803d').fontSize(9).font('Helvetica-Bold').text('✓ DIGITALLY SIGNED & VERIFIED VIA 2-STEP SMS OTP', 60, badgeY);
    doc.fillColor('#166534').fontSize(8).font('Helvetica').text(`Signed By: ${data.tenant_name} (${data.tenant_phone || 'Verified Handset'})`, 60, badgeY + 14);
    doc.text(`Timestamp (EAT): ${data.signed_at || new Date().toISOString()}`, 60, badgeY + 26);
    doc.text(`Verification Hash (SHA-256): ${data.signature_hash || 'SHA256-MUTUNE-SECURE-LEAD-9988'}`, 60, badgeY + 38);
    doc.fillColor('#15803d').font('Helvetica-Bold').text(`Legal Status: Enforceable Electronic Signature (Kenya Information & Communications Act)`, 60, badgeY + 50);
    doc.y = badgeY + 68;
  } else {
    doc.moveDown(1.5);
    doc.fontSize(9).font('Helvetica').fillColor('#475569');
    doc.text('_____________________________                  _____________________________');
    doc.text('Landlord / Authorized Agent Signature          Tenant Signature');
  }
}

function renderDemandNote(doc, data) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#dc2626').text('FORMAL 7-DAY DEMAND NOTE FOR OVERDUE RENT', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(10).font('Helvetica').fillColor('#334155');
  doc.text(`DATE OF NOTICE: ${new Date().toLocaleDateString('en-KE')}`);
  doc.text(`TO TENANT: ${data.tenant_name || 'Valued Tenant'} (${data.tenant_code || 'N/A'})`);
  doc.text(`UNIT: ${data.unit_number || 'N/A'}, ${data.property_name || 'Property'}`);
  doc.moveDown(1);

  doc.fillColor('#dc2626').font('Helvetica-Bold').text('FINAL REMINDER BEFORE LEGAL ACTION / DISTRESS FOR RENT:');
  doc.font('Helvetica').fillColor('#334155').text(`Our records indicate that your rent account is currently in arrears by KES ${(data.arrears_kes || 0).toLocaleString('en-KE')}.`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('BREAKDOWN OF OUTSTANDING BALANCE:');
  doc.font('Helvetica').text(`1. Overdue Monthly Rent: KES ${(data.rent_amount_kes || 0).toLocaleString('en-KE')}`);
  doc.text(`2. Late Payment Penalty Fee: KES ${(data.penalty_fee_kes || 500).toLocaleString('en-KE')}`);
  doc.font('Helvetica-Bold').text(`TOTAL AMOUNT DUE WITHIN 7 DAYS: KES ${(data.total_due_kes || (data.arrears_kes || 0)).toLocaleString('en-KE')}`);
  doc.moveDown(1.5);

  doc.text('Please clear this balance immediately via M-Pesa Paybill / Bank details provided in your portal.');
}

function renderQuitNotice(doc, data) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f172a').text('30-DAY NOTICE TO QUIT & VACATE PREMISES', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(10).font('Helvetica').fillColor('#334155');
  doc.text(`DATE OF ISSUANCE: ${new Date().toLocaleDateString('en-KE')}`);
  doc.text(`TENANT NAME: ${data.tenant_name || 'Tenant'} (${data.tenant_code || 'N/A'})`);
  doc.text(`PREMISES: Unit ${data.unit_number || 'N/A'}, ${data.property_name || 'Property'}`);
  doc.moveDown(1);

  doc.text(`You are hereby given 30 days notice to vacate the premises on or before ${data.vacate_date || '30 days from date hereof'}.`);
  doc.text('Please schedule a physical move-out damage survey with your property agent prior to handover to facilitate deposit refund processing.');
}

function renderLandlordStatement(doc, data) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f172a').text('MONTHLY LANDLORD REMITTANCE STATEMENT', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(10).font('Helvetica').fillColor('#334155');
  doc.text(`STATEMENT PERIOD: ${data.billing_month || new Date().toISOString().slice(0, 7)}`);
  doc.text(`LANDLORD: ${data.landlord_name || 'Landlord'} (${data.landlord_id || 'N/A'})`);
  doc.text(`PROPERTY: ${data.property_name || 'All Assigned Properties'}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('FINANCIAL SUMMARY (DUAL CURRENCY KES / USD):');
  doc.moveDown(0.5);

  const rate = data.usd_exchange_rate || 129.50;
  const grossKes = data.gross_collected_kes || 0;
  const mgmtFeeKes = data.management_fee_kes || 0;
  const netPayableKes = data.net_payable_kes || (grossKes - mgmtFeeKes);

  doc.font('Helvetica').text(`Gross Rent Collected: KES ${grossKes.toLocaleString('en-KE')}  ($${(grossKes / rate).toFixed(2)} USD)`);
  doc.text(`Less Management Commission (${data.commission_percent || 10}%): KES ${mgmtFeeKes.toLocaleString('en-KE')}  ($${(mgmtFeeKes / rate).toFixed(2)} USD)`);
  doc.font('Helvetica-Bold').fillColor('#10b981').text(`NET REMITTANCE PAYABLE: KES ${netPayableKes.toLocaleString('en-KE')}  ($${(netPayableKes / rate).toFixed(2)} USD)`);
  doc.fillColor('#334155').font('Helvetica').text(`Applied Live CBK Exchange Rate: 1 USD = ${rate} KES`);
}

function renderAgentSalaryVoucher(doc, data) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f172a').text('AGENT SALARY & COMMISSION PAYOUT VOUCHER', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(10).font('Helvetica').fillColor('#334155');
  doc.text(`PAYROLL CODE: ${data.payroll_code || 'PAY-VOUCHER'}`);
  doc.text(`AGENT NAME: ${data.agent_name || 'Field Agent'}`);
  doc.text(`EARB LICENSE: ${data.earb_license || 'N/A'}`);
  doc.text(`BILLING MONTH: ${data.billing_month || new Date().toISOString().slice(0, 7)}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('ITEMIZED EARNINGS & WITHHOLDINGS:');
  doc.font('Helvetica').text(`1. Letting Commission: KES ${(data.letting_commission_kes || 0).toLocaleString('en-KE')}`);
  doc.text(`2. Property Management Commission: KES ${(data.management_commission_kes || 0).toLocaleString('en-KE')}`);
  doc.text(`3. Property Initiation Fees: KES ${(data.initiation_fees_kes || 0).toLocaleString('en-KE')}`);
  doc.font('Helvetica-Bold').text(`GROSS EARNINGS: KES ${(data.gross_earnings_kes || 0).toLocaleString('en-KE')}`);
  doc.fillColor('#dc2626').font('Helvetica').text(`Less Withholding Tax (5% Resident Rate): -KES ${(data.withholding_tax_kes || 0).toLocaleString('en-KE')}`);
  doc.fillColor('#10b981').font('Helvetica-Bold').text(`NET AMOUNT DISBURSED (M-PESA B2C): KES ${(data.net_payable_kes || 0).toLocaleString('en-KE')}`);
}

function renderETIMSReceipt(doc, data) {
  doc.fontSize(14).font('Helvetica-Bold').fillColor('#0f172a').text('KRA eTIMS OFFICIAL TAX INVOICE RECEIPT', { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(10).font('Helvetica').fillColor('#334155');
  doc.text(`KRA INVOICE NUMBER: ${data.etims_invoice_number || `ETIMS-${Date.now()}`}`);
  doc.text(`CU SERIAL NUMBER: ${data.cu_serial_number || process.env.KRA_ETIMS_DEVICE_SERIAL || 'KRA-CU-DEVICE'}`);
  doc.text(`TAXPAYER PIN: ${data.taxpayer_pin || process.env.KRA_ETIMS_PIN || 'P000000000X'}`);
  doc.text(`DATE & TIME: ${new Date().toLocaleString('en-KE')}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('TAX BREAKDOWN:');
  const taxable = data.taxable_amount_kes || 10000;
  const vat = Math.round(taxable * 0.16);
  doc.font('Helvetica').text(`Taxable Amount (Excl. VAT): KES ${taxable.toLocaleString('en-KE')}`);
  doc.text(`Value Added Tax (16% VAT Rate): KES ${vat.toLocaleString('en-KE')}`);
  doc.font('Helvetica-Bold').fillColor('#10b981').text(`TOTAL ETIMS INVOICE AMOUNT: KES ${(taxable + vat).toLocaleString('en-KE')}`);
}

/**
 * Step 4.4: Rent Restriction Tribunal (RRT) Landlord Complaint Form (Cap 301 Part III)
 */
function renderRRTComplaintForm(doc, data) {
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#0f172a').text('IN THE RENT RESTRICTION TRIBUNAL AT MOMBASA', { align: 'center' });
  doc.fontSize(10).font('Helvetica-Bold').text('TRIBUNAL CASE NO: RRT/MBA/' + (data.case_number || 'PENDING-2026'), { align: 'center' });
  doc.moveDown(1);

  doc.fontSize(9.5).font('Helvetica-Bold').fillColor('#334155');
  doc.text(`LANDLORD / APPLICANT: ${data.landlord_name || 'Landlord Name'}`);
  doc.text('VERSUS');
  doc.text(`TENANT / RESPONDENT: ${data.tenant_name || 'Tenant Name'} (Unit ${data.unit_number || 'N/A'}, ${data.property_name || 'Property'})`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').fillColor('#0f172a').text('LANDLORD COMPLAINT & EVICTION APPLICATION UNDER CAP 301:');
  doc.moveDown(0.5);

  doc.font('Helvetica').fillColor('#334155');
  doc.text(`1. The Applicant is the lawful owner / appointed agent of the premises known as ${data.property_name || 'Property'}, Unit ${data.unit_number || 'N/A'}.`);
  doc.text(`2. The Respondent is in occupation of the said premises at an agreed standard monthly rent of KES ${(data.rent_amount_kes || 0).toLocaleString('en-KE')}.`);
  doc.text(`3. The Respondent has failed and/or neglected to pay rent arrears accumulating to KES ${(data.arrears_kes || 0).toLocaleString('en-KE')} despite service of a formal 7-Day Demand Note.`);
  doc.text('4. GROUNDS OF COMPLAINT: Continuous non-payment of rent, breach of tenancy covenant, and refusal to yield vacant possession.');
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('RELIEF SOUGHT BY APPLICANT:');
  doc.font('Helvetica');
  doc.text('a) An order for immediate vacant possession and eviction of the Respondent.');
  doc.text(`b) An order for payment of rent arrears in the sum of KES ${(data.arrears_kes || 0).toLocaleString('en-KE')}.`);
  doc.text('c) Distress for rent and costs of this application.');
  doc.moveDown(2);

  doc.text('DATED at Mombasa this ' + new Date().toLocaleDateString('en-KE'));
  doc.moveDown(1.5);
  doc.text('_____________________________________');
  doc.text('APPLICANT / ADVOCATE FOR THE APPLICANT');
}

/**
 * Step 4.4: Rent Restriction Tribunal (RRT) Tenant Response Form (Cap 301 Part III)
 */
function renderRRTResponseForm(doc, data) {
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#0f172a').text('IN THE RENT RESTRICTION TRIBUNAL AT MOMBASA', { align: 'center' });
  doc.fontSize(10).font('Helvetica-Bold').text('TRIBUNAL CASE NO: RRT/MBA/' + (data.case_number || 'PENDING-2026'), { align: 'center' });
  doc.moveDown(1);

  doc.fontSize(9.5).font('Helvetica-Bold').fillColor('#334155');
  doc.text(`TENANT / APPLICANT: ${data.tenant_name || 'Tenant Name'} (Unit ${data.unit_number || 'N/A'})`);
  doc.text('VERSUS');
  doc.text(`LANDLORD / RESPONDENT: ${data.landlord_name || 'Landlord Name'}`);
  doc.moveDown(1);

  doc.font('Helvetica-Bold').fillColor('#0f172a').text('TENANT STATEMENT OF DISPUTE / RESPONSE TO ILLEGAL RENT INCREASE:');
  doc.moveDown(0.5);

  doc.font('Helvetica').fillColor('#334155');
  doc.text(`1. The Tenant occupies Unit ${data.unit_number || 'N/A'} at ${data.property_name || 'Property'} under protected tenancy provisions of the Rent Restriction Act (Cap 301).`);
  doc.text(`2. The Landlord has unlawfully increased monthly rent from KES ${(data.standard_rent_kes || data.rent_amount_kes || 0).toLocaleString('en-KE')} to KES ${(data.demanded_rent_kes || (data.rent_amount_kes * 1.3)).toLocaleString('en-KE')} without standard rent assessment by this Tribunal.`);
  doc.text('3. The Tenant has consistently tendered lawful standard rent which the Respondent has declined or threatened illegal distress.');
  doc.moveDown(1);

  doc.font('Helvetica-Bold').text('ORDERS PRAYED FOR:');
  doc.font('Helvetica');
  doc.text('a) An injunction restraining the Landlord from unlawful eviction, harassment, or disconnection of water/power utilities.');
  doc.text('b) Determination of Standard Rent for the subject unit by the Tribunal Valuer.');
  doc.text('c) Costs of this application.');
  doc.moveDown(2);

  doc.text('DATED at Mombasa this ' + new Date().toLocaleDateString('en-KE'));
  doc.moveDown(1.5);
  doc.text('_____________________________________');
  doc.text('TENANT / ADVOCATE FOR THE TENANT');
}

function renderGenericDocument(doc, data) {
  doc.fontSize(12).font('Helvetica').text(JSON.stringify(data, null, 2));
}

module.exports = {
  generateLegalPDF
};
